export const copy = {
  nav: {
    dashboard: 'Dashboard',
    devices: 'Devices & Staff',
    company: 'Company',
    profile: 'Profile',
    marketplace: 'Marketplace',
  },
  dashboard: {
    hero: 'Your security posture at a glance.',
    activeAlerts: 'Active Alerts',
    offlineDevices: 'Offline Devices',
    mttr: 'MTTR',
    coverage: 'Coverage',
    proactiveRecommendations: 'Proactive Recommendations',
    noRecommendations: 'Your setup is fully optimized at the moment. No action required.',
  },
  devices: {
    title: 'Devices & Staff',
    subtitle: 'Monitor your security infrastructure and team access.',
    totalDevices: 'Total Devices',
    onlineDevices: 'Online Devices',
    offlineDevices: 'Offline Devices',
    staffMembers: 'Staff Members',
    activeStaff: 'Active Staff',
  },
  company: {
    title: 'Company',
    subtitle: 'Manage your organization settings and security policies.',
    companyName: 'Company Name',
    industry: 'Industry',
    size: 'Company Size',
    location: 'Location',
    securityLevel: 'Security Level',
  },
  profile: {
    title: 'Profile',
    subtitle: 'Your account settings and preferences.',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    department: 'Department',
    lastLogin: 'Last Login',
  },
  marketplace: {
    title: 'Marketplace',
    subtitle: 'Discover security solutions and integrations.',
    featured: 'Featured Solutions',
    categories: 'Categories',
    integrations: 'Integrations',
    recommendations: 'Personalized Recommendations',
  },
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    status: {
      online: 'Online',
      offline: 'Offline',
      warning: 'Warning',
      error: 'Error',
      success: 'Success',
    },
  },
} as const
